server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:chatdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

gemini:
  api:
    key: AIzaSyA0DhaC9DjHCU0iCYgP-Kj4tH3TaKtSeNU
